# POST http://localhost:3000/auth/signup
# Content-Type: application/json

# {  
#     "firstName":"new1",
#     "lastName": "new2",
#     "email":"new3@gmail.com", 
#     "password":"Demo123*" 
# }

# POST http://localhost:3000/auth/login
# Content-Type: application/json

# {  
#     "email":"demo3@gmail.com", 
#     "password":"Demo123*" 
# }

POST  http://localhost:3000/user/fetchAllUsers
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YmQxNjM0YzMwZmI4NzM5YTljN2M3MiIsImlhdCI6MTcwNjg5MDgwNH0.Bg9e25qlGss4iqupc_j9g3B81c2wNKIaHANBpta_7ww
